typescript:
- changed-files:
  - any-glob-to-any-file: '**/*.ts'

python:
- changed-files:
  - any-glob-to-any-file: '**/*.py'

'action provider':
- changed-files:
  - any-glob-to-any-file:
    - '**/action-providers/**'
    - '**/action_providers/**'

'wallet provider':
- changed-files:
  - any-glob-to-any-file:
    - '**/wallet-providers/**'
    - '**/wallet_providers/**'

'framework extension':
- changed-files:
  - any-glob-to-any-file: '**/framework-extensions/**'

documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'

example:
- changed-files:
  - any-glob-to-any-file: '**/examples/**'
