name: 🐛 Bug Report
description: Create a report to help us reproduce and fix the bug

body:
- type: markdown
  attributes:
    value: >
      #### Before submitting a bug, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/coinbase/agentkit/issues).
- type: checkboxes
  attributes:
    label: Language Affected
    description: Which language implementation is affected by this bug?
    options:
      - label: Python
      - label: TypeScript
  validations:
    required: true
- type: textarea
  attributes:
    label: 🐛 Describe the bug
    description: |
      Please provide a clear and concise description of what the bug is.

      If relevant, add a minimal example so that we can reproduce the error by running the code. It is very important for the snippet to be as succinct (minimal) as possible, so please take time to trim down any irrelevant code to help us debug efficiently. We are going to copy-paste your code and we expect to get the same result as you did: do NOT include any credentials, avoid any external data, and include the relevant imports, etc. For example:

      ```python
      # All necessary imports at the beginning
      from coinbase_agentkit import (
          AgentKit, 
          AgentKitConfig, 
          CdpWalletProvider,
          CdpWalletProviderConfig,
          cdp_wallet_action_provider
      )
      from coinbase_agentkit_langchain import get_langchain_tools

      # A succinct reproducing example trimmed down to the essential parts:
      cdp_config = CdpWalletProviderConfig(
          network_id="base-sepolia"
      )
      wallet_provider = CdpWalletProvider(cdp_config)
      agentkit = AgentKit(AgentKitConfig(
          wallet_provider=wallet_provider,
          action_providers=[
              cdp_wallet_action_provider()
          ]
      ))
      tools = get_langchain_tools(agentkit)  # Note: the bug is here, the method raises an error
      ```

      ```typescript
      # All necessary imports at the beginning
      import { AgentKit, CdpWalletProvider, cdpWalletActionProvider } from '@coinbase/agentkit';
      import { getLangChainTools } from '@coinbase/agentkit-langchain';

      # A succinct reproducing example trimmed down to the essential parts:
      const config = {
        networkId: "base-sepolia"
      };

      const walletProvider = await CdpWalletProvider.configureWithWallet(config);
      const agentkit = await AgentKit.from({
        walletProvider,
        actionProviders: [
          cdpWalletActionProvider()
        ]
      });

      const tools = await getLangChainTools(agentkit);  // Note: the bug is here, the method raises an error
      ```

      If the code is too long (hopefully, it isn't), feel free to put it in a public gist and link it in the issue: https://gist.github.com.

      Please also paste or describe the results you observe instead of the expected results. If you observe an error, please paste the error message including the **full** traceback of the exception. It may be relevant to wrap error messages in ```` ```triple quotes blocks``` ````.
    placeholder: |
      A clear and concise description of what the bug is.

      ```python
      # Sample code to reproduce the problem
      ```

      ```
      The error message you got, with the full traceback.
      ```
  validations:
    required: true
- type: textarea
  attributes:
    label: Versions
    description: |
      Please run the following commands based on your affected language and paste the output below.

      For Python:
      ```sh
      python --version
      poetry --version
      pip show coinbase-agentkit
      pip show coinbase-agentkit-langchain  # if using LangChain extension
      ```

      For TypeScript:
      ```sh
      node --version
      npm list @coinbase/agentkit
      npm list @coinbase/agentkit-langchain  # if using LangChain extension
      ```
  validations:
    required: true
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
