version: '3'

services:
  # Simple web application that will be attested
  attestable-app:
    image: public.ecr.aws/s7a1v0l4/marlin-testbox:latest
    ports:
      - "3222:3222"
    environment:
      - NODE_ENV=production
      - PORT=3222
    restart: always
    command: ["node", "index.js"]
    volumes:
      - /tmp/app-data:/app/data

  # Health monitoring endpoint
  health-check:
    image: public.ecr.aws/s7a1v0l4/marlin-testbox:latest
    ports:
      - "8080:8080"
    environment:
      - CHECK_INTERVAL=60
      - REPORT_PATH=/health
    command: ["node", "health.js"]
    depends_on:
      - attestable-app
