version: '3.8'

services:
  attestation-service:
    image: auto-trader-auto-trader:latest
    ports:
      - "3222:3222"  # Main application port
      - "1300:1300"  # Attestation service port
    environment:
      - NODE_ENV=production
      - PORT=3222
      - ENABLE_AGENTKIT=true
      - ENABLE_COLLABORATION=true
      - ENABLE_WEBSOCKETS=true
      - MARLIN_ENCLAVE=true
      - ENABLE_ATTESTATION=true
      - ATTESTATION_PORT=1300
      - RECALL_MEMORY_MODE=in-memory
    restart: unless-stopped
    network_mode: host  # Required for Marlin CVM
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3222/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
