services:
  auto-trader:
    image: cyama/auto-trader:latest
    ports:
      - "3222:3222"
    restart: always
    command: sh -c "node -e \"const http=require('http');const server=http.createServer((req,res)=>{res.writeHead(200);res.end('4g3n7 AutoTrader Running on CVM!');});server.listen(3222,'0.0.0.0',()=>console.log('Server running at http://0.0.0.0:3222/'));\""
    environment:
      - NODE_ENV=production
      - PORT=3222
